### ISSUE TITLE
Invalid HTML not causing an error

### ISSUE THREAD

**Issue by HaleTom** [ericbeland/html_validation#13] opened 2016-07-26 02:05 UTC
How can I ensure that html_validation is running?

In my `test/test_helper.rb` I have

```
require 'html_validation'                 
include PageValidations                   
HaveValidHTML.show_html_in_failures = true
```

I have a test:

``` ruby
test 'valid login' do     
  assert have_valid_html  
  get login_path          
  post login_path params: 

  assert_redirected_to @user
  follow_redirect!        
  assert have_valid_html  
end
```

When these pages render in my browser, it displays the incorrect nesting in the source view:
`<B><I>Test - Incorrect nesting</B></I>`

.... but I get no output from html_validation.

**Comment by ericbeland** [comment] 2016-07-26 03:50
The validation is a lightweight wrapper around HTML tidy, so the way to debug this is to save the HTML off and run it through HTML tidy directly. If HTML tidy doesn't see the issue, then that's something that can be reported to them. If it does, it is probably a config issue. 

To debug, I'd get the HTML by writing the contents of page.body to a file right before the last assert happens in your test and then verify that it looks wrong there. You can then take that, and pass it in to tidy on the command line and confirm it sees the problem by looking at the error output it gives.

**Comment by ericbeland** [comment] 2016-09-08 14:55
If you were getting any differences vs. what HTML Tidy returns, please let me know.  Opening a bug against tidy might be appropriate in that case.

I'm closing this, but let me know if you keep having trouble and it looks like it isn't a Tidy thing.

**Comment by HaleTom** [comment] 2016-09-10 10:11
I put purposefully invalid code in my `_header.html.erb` which is in included in every page. I loaded a page in the browser and put its source into a file called `html`. 

```
@ravi@boxy:~/prj/sample_app(Ch10-users-CRUD*% u=)$ tidy html > /dev/null
line 30 column 5 - Error: <header> is not recognized!
line 30 column 5 - Warning: discarding unexpected <header>
line 33 column 5 - Error: <nav> is not recognized!
line 33 column 5 - Warning: discarding unexpected <nav>
line 47 column 20 - Warning: discarding unexpected <head>
line 47 column 30 - Warning: replacing unexpected b by </b>
line 47 column 54 - Warning: inserting implicit <i>
line 42 column 13 - Warning: missing </ul> before </li>
line 49 column 11 - Warning: discarding unexpected </li>
line 51 column 5 - Warning: discarding unexpected </nav>
line 53 column 1 - Warning: discarding unexpected </header>
line 57 column 3 - Error: <aside> is not recognized!
line 57 column 3 - Warning: discarding unexpected <aside>
line 58 column 5 - Error: <section> is not recognized!
line 58 column 5 - Warning: discarding unexpected <section>
line 63 column 5 - Warning: discarding unexpected </section>
line 64 column 3 - Warning: discarding unexpected </aside>
line 72 column 7 - Error: <footer> is not recognized!
line 72 column 7 - Warning: discarding unexpected <footer>
line 77 column 3 - Error: <nav> is not recognized!
48 warnings, 6 errors were found!

This document has errors that must be fixed before
using HTML Tidy to generate a tidied up version.

To learn more about HTML Tidy see http://tidy.sourceforge.net
Please fill bug reports and queries using the "tracker" on the Tidy web site.
Additionally, questions can be sent to html-tidy@w3.org
HTML and CSS specifications are available from http://www.w3.org/
Lobby your company to join W3C, see http://www.w3.org/Consortium
@ravi@boxy:~/prj/sample_app(Ch10-users-CRUD*% u=)[2]$ 
```

Tidy seems to be doing its job, is there anything else I can check for?

**Comment by ericbeland** [comment] 2016-10-11 16:44
Hey Tom, can you try this? Can you grab the full HTML for the outputted page and put it in a gist? If I have the files to reproduce, I'll take a look at it and see if it works or not and reopen this.

**Comment by ericbeland** [comment] 2016-10-11 16:46
It *could* be a minitest issue I suppose. I think I wrote RSpec matchers--I haven't messed around with minitest in particular.

**Closed** 2018-01-01 00:32 UTC
